import { SIGN_IN_FAILURE_EVENT, SIGN_IN_SUCCESS_EVENT, SIGN_UP_AWAITING_EVENT, SIGN_UP_FAILURE_EVENT } from "./action.events";

export type SignInActorEvents = 
  | SIGN_IN_SUCCESS_EVENT
  | SIGN_IN_FAILURE_EVENT;

export type SignUpActorEvents = 
  | SIGN_UP_AWAITING_EVENT
  | SIGN_UP_FAILURE_EVENT