import { DONE_INVOKE_HYDRATE_EVENT, SIGN_IN_SUCCESS_EVENT, SIGN_UP_COMPLETED_EVENT } from "./auth.events";

export type PersistAuthEvent =
    | SIGN_IN_SUCCESS_EVENT
    | SIGN_UP_COMPLETED_EVENT
    | DONE_INVOKE_HYDRATE_EVENT;