import { SIGN_IN_FAILURE_EVENT, SIGN_IN_SUCCESS_EVENT, SIGN_UP_SUCCESS_EVENT, SIGN_UP_FAILURE_EVENT, REGISTRATION_VERIFICATION_FAILURE_EVENT, REGISTRATION_VERIFICATION_EXPIRED_EVENT, REGISTRATION_VERIFICATION_SUCCESS_EVENT } from "./auth.events";

export type SignInActorEvents = 
  | SIGN_IN_SUCCESS_EVENT
  | SIGN_IN_FAILURE_EVENT;

export type SignUpActorEvents = 
  | SIGN_UP_SUCCESS_EVENT
  | SIGN_UP_FAILURE_EVENT

export type RegistrationVerificationActorEvents =
  | REGISTRATION_VERIFICATION_SUCCESS_EVENT
  | REGISTRATION_VERIFICATION_FAILURE_EVENT
  | REGISTRATION_VERIFICATION_EXPIRED_EVENT;