import { DONE_ACTOR_CHECK_AUTH_EVENT, SIGN_IN_SUCCESS_EVENT, VERIFICATION_COMPLETED_EVENT } from "./auth.events";

export type PersistAuthEvent =
    | SIGN_IN_SUCCESS_EVENT
    | VERIFICATION_COMPLETED_EVENT
    | DONE_ACTOR_CHECK_AUTH_EVENT;