import { SIGN_IN_FAILURE_EVENT, SIGN_IN_SUCCESS_EVENT, SIGN_UP_SUCCESS_EVENT, SIGN_UP_FAILURE_EVENT, VERIFY_EMAIL_EXPIRED_EVENT, VERIFY_EMAIL_COMPLETED_EVENT, VERIFY_EMAIL_NOT_COMPLETED_EVENT } from "./auth.events";

export type SignInActorEvents = 
  | SIGN_IN_SUCCESS_EVENT
  | SIGN_IN_FAILURE_EVENT;

export type SignUpActorEvents = 
  | SIGN_UP_SUCCESS_EVENT
  | SIGN_UP_FAILURE_EVENT

export type VerifyEmailActorEvents =
  | VERIFY_EMAIL_COMPLETED_EVENT
  | VERIFY_EMAIL_NOT_COMPLETED_EVENT
  | VERIFY_EMAIL_EXPIRED_EVENT;