import { DONE_ACTOR_CHECK_AUTH_EVENT, VERIFY_EMAIL_SUCCESS_EVENT, SIGN_IN_SUCCESS_EVENT } from "./auth.events.types";

export type PersistAuthEvent =
    | SIGN_IN_SUCCESS_EVENT
    | VERIFY_EMAIL_SUCCESS_EVENT
    | DONE_ACTOR_CHECK_AUTH_EVENT;